//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class Titulos {
    
    private TitulosTitulo[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Titulo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public TitulosTitulo[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class TitulosTitulo {
    
    private string protocoloField;
    
    private string nomeDevedorField;
    
    private string documentoDevedorField;
    
    private string nomeApresentanteField;
    
    private string documentoApresentanteField;
    
    private string nomeCredorField;
    
    private string documentoCredorField;
    
    private string numeroTituloField;
    
    private string valorTituloField;
    
    private string dataEmissaoField;
    
    private string especieTituloField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Protocolo {
        get {
            return this.protocoloField;
        }
        set {
            this.protocoloField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string NomeDevedor {
        get {
            return this.nomeDevedorField;
        }
        set {
            this.nomeDevedorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DocumentoDevedor {
        get {
            return this.documentoDevedorField;
        }
        set {
            this.documentoDevedorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string NomeApresentante {
        get {
            return this.nomeApresentanteField;
        }
        set {
            this.nomeApresentanteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DocumentoApresentante {
        get {
            return this.documentoApresentanteField;
        }
        set {
            this.documentoApresentanteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string NomeCredor {
        get {
            return this.nomeCredorField;
        }
        set {
            this.nomeCredorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DocumentoCredor {
        get {
            return this.documentoCredorField;
        }
        set {
            this.documentoCredorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string NumeroTitulo {
        get {
            return this.numeroTituloField;
        }
        set {
            this.numeroTituloField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ValorTitulo {
        get {
            return this.valorTituloField;
        }
        set {
            this.valorTituloField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DataEmissao {
        get {
            return this.dataEmissaoField;
        }
        set {
            this.dataEmissaoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string EspecieTitulo {
        get {
            return this.especieTituloField;
        }
        set {
            this.especieTituloField = value;
        }
    }
}
